Annotate Licensing admin test as slow
This will triple the default timeout so the page can load. The timeout set for
waitForUR appears to be superseded by the global config causing an error:
  Error: page.waitForURL: Test timeout of 30000ms exceeded

Docs: https://playwright.dev/docs/api/class-test#test-slow