Increase the timeout for Licensing > Check licensing pages load
This will triple the default timeout (3s -> 9s) so the download can complete at
the test is consistently failing with

Error: page.waitForEvent: Test timeout of 30000ms exceeded. waiting for event
download